### ISSUE TITLE
illegal reflective access operation

### ISSUE THREAD

**Issue by aleksandersumowski** [benedekfazekas/mranderson#40]
When starting `lein repl` I get a number of warnings:
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by mranderson049.orchard.v0v4v0.dynapath.v0v2v5.dynapath.defaults$eval3663$fn__3664 to method java.net.URLClassLoader.addURL(java.net.URL)
> WARNING: Please consider reporting this to the maintainers of mranderson049.orchard.v0v4v0.dynapath.v0v2v5.dynapath.defaults$eval3663$fn__3664
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release

My profiles.clj:

```
{:system {:jvm-opts ["-Duser.timezone=UTC"]}
 :user  {:plugins  [[lein-ancient "0.6.15" :exclusions [org.clojure/clojure]]
                    [thomasa/mranderson "0.5.1"]
                    [cider/cider-nrepl "0.21.1"]
                    [lein-pprint "1.2.0"]
                    [jonase/eastwood "0.3.3"]
                    [lein-try "0.4.3"]]
         :dependencies [[com.bhauman/rebel-readline "0.1.4"]]
         :aliases {"rebl" ["trampoline" "run" "-m" "rebel-readline.main"]}
         :injections []}}

```

**Comment by benedekfazekas** [comment]
Thanks for reporting.

I think this is really coming from `[cider/cider-nrepl "0.21.1"]` or more precisely from its dependency `orchard` `0.4.0` and again its dependency `dynapath` `0.2.5`. I can see that latest HEAD `orchard` is using `dynapath` `1.0.0`

I think the issue is discussed here in detail: https://github.com/clojure-emacs/orchard/issues/20

MrAnderson only gets into this story because its name was used as a prefix when `cider-nrepl` inlined its dependencies, including transient ones.

Hope this makes sense.
